### ISSUE TITLE
[Question] Personalization API reference

### ISSUE THREAD

**Issue by nachaos** [DynamicYield/server-side-reference-app#1]
Hi. I am in the process of evaluating the tool and its capabilities, and find out this repository very useful.
I am wondering if there's a **Personalization API** reference/guide/documentation somewhere on the DY website/knowledge base, so far I wasn't able to find nothing an nobody on the live chat was able to help me on this.

@ramonsnir I would really appreciate your reply.

Thanks in advance,
Nacho.

**Comment by ramonsnir** [comment]
Hi Nacho,

This is a separate Dynamic Yield product that is currently in a closed beta. If you are interested, please reach out to your CSM who will see if your company is a good fit for our beta program. If you are we'll gladly share the product guide.

Thanks,
Ramon

**Comment by nachaos** [comment]
Thanks for your answer Ramon, we'll reach them probably then.
